development: &development
  adapter: postgresql
  encoding: unicode
  database: rubykaigi2013_development
  pool: 5
  username: postgres
  password:
  min_messages: warning

test: &test
  <<: *development
  database: rubykaigi2013_test
